### ISSUE TITLE
 fatal error: ./ust_myprog.h: No such file or directory

### ISSUE THREAD

**Issue by Zeeshanhayat** [tracecompass/xml-analysis-example#1]
Hi, I changed your makefile to add the path but I am getting this error:

 fatal error: ./ust_myprog.h: No such file or directory.

changed gcc line is:
gcc -O2 -I /lttng/2.8.6/include -o myprog myprog.c tp.c -ldl -llttng-ust -fopenmp

Could you please tell me how I can remove this error.

**Comment by alexmonthy** [comment]
You are missing the `-I.` part (it could also be written `-I .`) The `.` refers to the current directory, so you need to tell the compiler to include it so it can find `ust_myprog.h`.

**Comment by Zeeshanhayat** [comment]
If I make the changes:
gcc -O2 -I. -ldl -llttng-ust -fopenmp

I am getting this error:

In file included from tp.c:18:0:
ust_myprog.h:25:30: fatal error: lttng/tracepoint.h: No such file or directory
 #include <lttng/tracepoint.h>
                              ^
compilation terminated.

Do I have to add path to LTTng?

**Comment by alexmonthy** [comment]
Yes, you still need the path to the LTTng libs. You can use several `-I` directives. In the [Makefile](https://github.com/tracecompass/xml-analysis-example/blob/master/program/Makefile) I only include `-I.` because I expect the libraries to be installed in a path included by default (like `/usr/lib/*` or `/usr/local/lib`).

In your comment you indicated using `-I /lttng/2.8.6/include`, I assume this is where you installed LTTng? In this case your command line should look like this:

    gcc -O2 -I . -I /lttng/2.8.6/include -o myprog myprog.c tp.c -ldl -llttng-ust -fopenmp

If you installed in a non-default location, you will probably need to set `-L` correctly so that it knows where to find `-llttng-ust`. See https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html .

**Comment by Zeeshanhayat** [comment]
It is working now. Thanks :)

**Comment by alexmonthy** [comment]
Great, no problem!
